<?php
/**
 *
 *
 * All rights reserved.
 *
 * @author Okulov Anton
 * @email qantus@mail.ru
 * @version 1.0
 * @company HashStudio
 * @site http://hashstudio.ru
 * @date 04/08/16 10:42
 */

namespace Modules\Mail;

use Modules\Mail\Forms\SettingsForm;
use Modules\Mail\Models\Settings;
use Phact\Module\Module;

class MailModule extends Module
{
    public static function getVerboseName()
    {
        return "Почта"; // TODO: Change the autogenerated stub
    }

    public static function getSettingsForm()
    {
        return new SettingsForm();
    }

    public static function getSettingsModel()
    {
        return new Settings();
    }
}